export const MAX_COMPLETED_EXCHANGES = 4;
export const MAX_PRIOR_EVIDENCE_REFS = 4;
export const MAX_CONTEXT_MESSAGE_SCAN = 32;
export const MAX_CONTEXT_SOURCE_DEPTH = 4;
export const MAX_CONTEXT_ARRAY_ITEMS = 100;
export const MAX_CONTEXT_OBJECT_KEYS = 32;
export const MAX_CONTEXT_STRING_LENGTH = 4_000;
export const MAX_SEMANTIC_VALUE_LENGTH = 512;
export const MAX_CONTEXT_METADATA_BYTES = 16 * 1024;

