import { Injectable } from '@nestjs/common'; import { IdxSemanticError } from './semantic.error';
const ACTIONS = [['Insert', 'insert'], ['Update', 'update'], ['Delete', 'delete'], ['Print', 'print'], ['Import', 'import'], ['Export', 'export'], ['Copy', 'copy'], ['Approval', 'approval']] as const;
export type IdxAction = 'read' | typeof ACTIONS[number][1]; export type SemanticMenu = Readonly<{ menuId: string; actions: readonly IdxAction[] }>;
const accepted = Symbol('accepted_menu_detail'); export type AcceptedMenuDetail = readonly SemanticMenu[] & Readonly<{ [accepted]: true }>;
const responseKeys = ['Code', 'ExecutionTime', 'Message', 'Version', 'Data']; const recordKeys = ['UUID', 'MenuID', 'Category', 'Patrilineal', 'Sorting', 'Memo', 'MenuNode', 'MenuPermission']; const permissionKeys = ['UUID', 'UUID_Menu', ...ACTIONS.map(([key]) => key), 'Others', 'Memo']; const nodeKeys = ['UUID', 'UUID_Menu', 'Language', 'MenuName', 'Icon', 'ProgramCode', 'ProgramPath', 'StartMethod', 'Memo'];
@Injectable() export class IdxMenuDetailValidator {
  validate(body: unknown): AcceptedMenuDetail { try { if (!exact(body, responseKeys) || body.Code !== 200 || !str(body.ExecutionTime) || !str(body.Message) || !str(body.Version) || !Array.isArray(body.Data)) fail(); const menus = body.Data.map(menu); Object.defineProperty(menus, accepted, { value: true }); return Object.freeze(menus) as AcceptedMenuDetail; } catch { fail(); } }
}
export function acceptedMenus(value: unknown): value is AcceptedMenuDetail { return Array.isArray(value) && (value as unknown as Record<symbol, unknown>)[accepted] === true; }
function menu(value: unknown): SemanticMenu { if (!exact(value, recordKeys) || !str(value.UUID) || !str(value.Category) || !nullable(value.Patrilineal) || !str(value.Sorting) || !str(value.Memo) || !Array.isArray(value.MenuNode)) fail(); for (const item of value.MenuNode) node(item); const id = menuId(value.MenuID); return Object.freeze({ menuId: id, actions: Object.freeze(permission(value.MenuPermission)) }); }
function node(value: unknown): void { if (!exact(value, nodeKeys) || !str(value.UUID) || !str(value.UUID_Menu) || !str(value.Language) || !str(value.MenuName) || !str(value.Icon) || !nullable(value.ProgramCode) || !str(value.ProgramPath) || !nullable(value.StartMethod) || !str(value.Memo)) fail(); }
function permission(value: unknown): IdxAction[] { if (!exact(value, permissionKeys) || !str(value.UUID) || !str(value.UUID_Menu) || value.Others !== null || !str(value.Memo)) fail(); const output: IdxAction[] = ['read']; for (const [field, action] of ACTIONS) { if (value[field] !== 'Y' && value[field] !== 'N') fail(); if (value[field] === 'Y') output.push(action); } return output; }
function menuId(value: unknown): string { if (!str(value)) fail(); const result = value.trim(); if (!result || control(result)) fail(); return result; }
function exact(value: unknown, keys: readonly string[]): value is Record<string, unknown> { return plain(value) && Reflect.ownKeys(value).length === keys.length && Reflect.ownKeys(value).every((key) => typeof key === 'string' && keys.includes(key)); }
function plain(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value) && Object.getPrototypeOf(value) === Object.prototype; } function str(value: unknown): value is string { return typeof value === 'string'; } function nullable(value: unknown): boolean { return value === null || str(value); } function control(value: string): boolean { return [...value].some((x) => { const code = x.codePointAt(0) ?? 0; return code <= 31 || code === 127; }); } function fail(): never { throw new IdxSemanticError(); }
